#!/bin/sh
case "$1" in
    start)
        start-stop-daemon --start --background --exec /usr/bin/aesdsocket -- -d
        ;;
    stop)
        start-stop-daemon --stop --exec /usr/bin/aesdsocket --signal SIGTERM
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
